# Generated by Django 2.0.1 on 2018-01-19 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rated_videos',
        ),
        migrations.AddField(
            model_name='translationvideo',
            name='voted_users',
            field=models.ManyToManyField(related_name='rated_videos', through='translations.UserVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
