# Generated by Django 2.0.1 on 2018-01-18 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationvideo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translationvideo',
            name='words',
            field=models.ManyToManyField(related_name='videos', to='translations.Word'),
        ),
    ]
