# Generated by Django 2.0.1 on 2018-01-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_auto_20180125_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationvideo',
            name='video_file',
            field=models.FileField(max_length=150, upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
