# Generated by Django 2.0.1 on 2018-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20180125_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTranslationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('words', models.CharField(max_length=200)),
                ('video_file', models.FileField(max_length=150, upload_to='deleted_videos/%Y/%m/')),
                ('votes', models.IntegerField()),
                ('upload_date', models.DateTimeField()),
                ('deleting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
