# Generated by Django 2.0.1 on 2018-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_deletedtranslationvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtranslationvideo',
            name='video_file',
            field=models.FileField(max_length=150, upload_to=''),
        ),
    ]
