# Generated by Django 2.0.1 on 2018-02-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0008_user_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='translationvideo',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='translationvideo',
            name='words',
        ),
        migrations.AddField(
            model_name='translationvideo',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='videoword',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.TranslationVideo'),
        ),
        migrations.AddField(
            model_name='videoword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Word'),
        ),
    ]
